
services:
  - type: web
    name: prothemesru
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements-debug.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 1 --timeout 30 --log-level debug app_debug:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true

databases:
  - name: prothemesru-db
    plan: free
