
services:
  - type: web
    name: prothemesru
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app_simple:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true

databases:
  - name: prothemesru-db
    plan: free
