
services:
  - type: web
    name: prothemesru
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: FLASK_ENV
        value: production

databases:
  - name: prothemesru-db
    plan: free
