
services:
  - type: web
    name: prothemesru
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -b 0.0.0.0:5000 wsgi:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: prothemesru-db
          property: connectionString
databases:
  - name: prothemesru-db
    plan: free
