
name: Autodeploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install backend deps
      run: |
        pip install -r requirements.txt

    - name: Build frontend
      working-directory: frontend
      run: |
        npm install
        npm run build
